-- FUNCÇOES DE DATAS

SELECT GETDATE() AS DATA_ATUAL , DATEDIFF(HOUR,2024-01-01,GETDATE()) AS HORAS_DO_INICIO_DO_ANO


-- CALCULANDO QUANTOS MESES/ANOS UMA PESSOA POSSUI

select NOME, DATA_DE_NASCIMENTO , 
DATEDIFF(MONTH,DATA_DE_NASCIMENTO,GETDATE()) AS MESES_DE_VIDA ,  
DATEDIFF(YEAR,DATA_DE_NASCIMENTO,GETDATE()) AS ANOS_DE_VIDA   
from TABELA_DE_CLIENTES;