-- FUNCÇOES DE DATAS

SELECT GETDATE() AS DATA_ATUAL , DATEDIFF(HOUR,2024-01-01,GETDATE()) AS HORAS_DO_INICIO_DO_ANO


-- CALCULANDO QUANTOS MESES/ANOS UMA PESSOA POSSUI

select NOME, DATA_DE_NASCIMENTO , 
DATEDIFF(MONTH,DATA_DE_NASCIMENTO,GETDATE()) AS MESES_DE_VIDA ,  
DATEDIFF(YEAR,DATA_DE_NASCIMENTO,GETDATE()) AS ANOS_DE_VIDA   
from TABELA_DE_CLIENTES;

-- DATA POR EXTENSO

SELECT NOME , DATENAME( DATA_DE_NASCIMENTO) AS EXTENSO FROM TABELA_DE_CLIENTES

SELECT 
    NOME,
    FORMAT(DATA_DE_NASCIMENTO, 'D', 'pt-BR') AS DataExtenso
FROM 
    TABELA_DE_CLIENTES;

	 --D MAIUSCULO = DATA POR ESTENSO => sábado, 1 de setembro de 1990