-- HAVING

SELECT NF.MATRICULA , COUNT (ITNF.NUMERO) AS QTD_VENDA , SUM(ITNF.PRECO) AS TOTAL_VENDAS FROM NOTAS_FISCAIS NF
INNER JOIN ITENS_NOTAS_FISCAIS ITNF 
ON ITNF.NUMERO = NF.NUMERO
GROUP BY NF.MATRICULA
HAVING SUM(ITNF.PRECO) > 840000
ORDER BY TOTAL_VENDAS DESC

------------------------------------------

--MOSTRANDO O PREÇO MAX E MIN DE PRODUTOS MAIOR QUE 10 E COM MAX MAIOR QUE 15

SELECT EMBALAGEM , MAX(PRECO_DE_LISTA) AS VALOR_MAX , MIN(PRECO_DE_LISTA) AS VALOR_MIN
FROM TABELA_DE_PRODUTOS
WHERE PRECO_DE_LISTA >= 10
GROUP BY EMBALAGEM
HAVING MAX(PRECO_DE_LISTA) <= 15;
---------------------------------------------

-- MOSTRANDO A SOMA DA QTD DE VENDA DOS PRODUTOS 

SELECT TABPRO.NOME_DO_PRODUTO , SUM( ITNF.QUANTIDADE) AS QTD_TOTAL 
FROM ITENS_NOTAS_FISCAIS ITNF
INNER JOIN TABELA_DE_PRODUTOS TABPRO
ON ITNF.CODIGO_DO_PRODUTO = TABPRO.CODIGO_DO_PRODUTO
GROUP BY TABPRO.NOME_DO_PRODUTO
ORDER BY QTD_TOTAL DESC;

--liste somente os produtos que venderam mais que 394000 unidades.
SELECT TABPRO.NOME_DO_PRODUTO , SUM( ITNF.QUANTIDADE) AS QTD_TOTAL 
FROM ITENS_NOTAS_FISCAIS ITNF
INNER JOIN TABELA_DE_PRODUTOS TABPRO
ON ITNF.CODIGO_DO_PRODUTO = TABPRO.CODIGO_DO_PRODUTO
GROUP BY TABPRO.NOME_DO_PRODUTO
HAVING SUM( ITNF.QUANTIDADE) > 394000
ORDER BY QTD_TOTAL DESC;
---------------------------------------------

-- MOSTRANDO O QUE MAIS VENDEU E O QUE MENOS VENDEU

WITH Totais AS (
					/* WITH É USADO COMO UMA TABELA TEMPORARIA (CHAMA CLAUSULA CTE) , que pode 
					ser referenciada pela consulta principal, facilitando a legibilidade e reutilização do código.*/
    SELECT TABPRO.NOME_DO_PRODUTO, 
           SUM(ITNF.QUANTIDADE) AS QTD_TOTAL,
           ROW_NUMBER() OVER (ORDER BY SUM(ITNF.QUANTIDADE) DESC) AS MAIOR_VENDA,
           ROW_NUMBER() OVER (ORDER BY SUM(ITNF.QUANTIDADE)) AS MENOR_VENDA
		   -- SUB CONSULTA PARA ALINHAR OS ITENS COM AS FUNÇÕES ASSIM PODEMOS USAR AS LINHAS DESSA SUB CONSULTA
    FROM ITENS_NOTAS_FISCAIS ITNF
    INNER JOIN TABELA_DE_PRODUTOS TABPRO ON ITNF.CODIGO_DO_PRODUTO = TABPRO.CODIGO_DO_PRODUTO
    GROUP BY TABPRO.NOME_DO_PRODUTO
)
SELECT NOME_DO_PRODUTO, QTD_TOTAL
FROM Totais
WHERE MAIOR_VENDA = 1 OR MENOR_VENDA = 1 --AQUI PEDIMOS PARA PUXAR APENAS A LINHA 1 DE CADA SUB CONSULTA
ORDER BY MAIOR_VENDA;
