-- DECOBRIR CLIENTES NOS MESMOS BAIRROS QUE VENDEDORES

SELECT DISTINCT COUNT (TC.BAIRRO) AS QTD_CLIENTES,  TC.BAIRRO  AS LOCAL_CLIENTES, TV.BAIRRO AS LOCAL_VENDEDORES FROM TABELA_DE_CLIENTES TC
RIGHT JOIN TABELA_DE_VENDEDORES TV
ON TC.BAIRRO = TV.BAIRRO
GROUP BY TC.BAIRRO, TV.BAIRRO;
--------------------------------------------------------

