---SUBCONSULTAS--

-- PARA USAR UMA SUB QUERY DENTRO DO IN É NECESSARIO QUE ELA POSSUA APENAS UM CAMPO

--SELECT DISTINCT BAIRRO FROM TABELA_DE_VENDEDORES;
/*Copacabana
Jardins
Santo Amaro
Tijuca*/



SELECT * FROM TABELA_DE_CLIENTES 
WHERE BAIRRO IN (SELECT DISTINCT BAIRRO FROM TABELA_DE_VENDEDORES);

-----------------------------------------------------------------

SELECT DISTINCT SABOR
FROM TABELA_DE_PRODUTOS
WHERE CODIGO_DO_PRODUTO IN (
    SELECT INF.CODIGO_DO_PRODUTO
    FROM ITENS_NOTAS_FISCAIS INF
    GROUP BY INF.CODIGO_DO_PRODUTO
    HAVING SUM(INF.QUANTIDADE) > 382544
);

