-- FUNÇÕES

select top 1 * from tabela_de_clientes;

SELECT TOP 4 NOME, LOWER(NOME) AS MINUSCULO, UPPER(NOME) AS MAIUSCULO FROM TABELA_DE_CLIENTES;

SELECT TOP 4 CONCAT(ENDERECO_1,' ',ENDERECO_2,' - ',BAIRRO,' - ',CIDADE,' - ',ESTADO) FROM TABELA_DE_CLIENTES;

--PEGANDO O PRIMEIRO NOME DE UMA STRING

SELECT TOP 8 NOME, CHARINDEX(' ', NOME, 1) FROM TABELA_DE_CLIENTES;

--CHARINDEX >>>> PROCURAR ALGO (ESPAÇO) , DENTRO DA COLUNA (NOME), COMEÇANDO PELA POSIÇÃO (1)

SELECT TOP 8 NOME, SUBSTRING(NOME, 1, CHARINDEX(' ', NOME, 1)) FROM TABELA_DE_CLIENTES;

SELECT GETDATE()AS AGORA, DATEADD(DAY,10,GETDATE()) AS "+10_DIAS";

